model:
  checkpoint_path: "yerevann/chemma-2b"
  tokenizer_path: "yerevann/chemma-2b"
  mol_tags: ["[START_SMILES]", "[END_SMILES]"]
  pad_token: "<pad>"
  sim_tags: ["[SIMILAR]", "[/SIMILAR]"]
  device: "cuda"
  dtype: "fp32" # bf16 / fp32

generation:
  max_new_tokens: 500
  temperature: 1.0
  do_sample: true
  repetition_penalty: 1.01
  num_return_sequences: 1

genetic:
  pool_size: 30
  num_prompts: 100
  num_similars: 1
  representation: "smiles"
  sim_vals: [0.6, 0.9]

oracle:
  name: "geam.parp1"
  max_calls: 3000
  log_dir: "results/genetic/chemma_2b/dock.parp1"