[model]
checkpoint_path = "/nfs/h100/raid/chem/checkpoints/hf-4.49.0/yerevann/Llama-3-750M/1575ffbf00b242dcadcb7a25/step-20000"
tokenizer_path = "/nfs/h100/raid/chem/checkpoints/tokenizers/Llama-3.2-chem-1B-v1"
representation = "smiles"
mol_tags = ["[SMILES]", "[/SMILES]"]
sim_tags = ["[SIMILAR]", "[/SIMILAR]"]
pad_token = "<|finetune_right_pad_id|>"
device = "cuda"
dtype = "bf16" # bf16 / fp32
gen_batch_size = 100000 # put a large number if batched generation is not needed

[generation]
max_new_tokens = 500
temperature = 1.0
do_sample = true
repetition_penalty = 1.01
num_return_sequences = 1

[genetic]
pool_size = 30
num_prompts = 30
num_similars = 1
sim_vals = [0.4, 0.9]
temp_schedule = [1.1, 1.1]