model:
  checkpoint_path: "yerevann/ChemLlama-3B"
  tokenizer_path: "yerevann/ChemLlama-3B"
  mol_tags: ["[SMILES]", "[/SMILES]"]
  pad_token: <|finetune_right_pad_id|>
  sim_tags: ["[SIMILAR]", "[/SIMILAR]"]
  device: cuda
  dtype: fp32 # bf16 / fp32

generation:
  max_new_tokens: 500
  temperature: 1.0
  do_sample: true
  repetition_penalty: 1.01
  num_return_sequences: 1

genetic:
  pool_size: 20
  num_prompts: 50
  num_similars: 2
  representation: "smiles"
  sim_vals: [0.6, 0.9]

oracle:
  task_name: ""
  max_calls: 
  log_dir: ""
  reward_type: ""
