model:
  # checkpoint_path: ${oc.env:OUT_DIR}/hf-4.49.0/yerevann/Llama-3-380M/6843cdf3239f4e80810b4125/step-20000
  # tokenizer_path: ${oc.env:OUT_DIR}/tokenizers/Llama-3.2-chem-1B-v1
  checkpoint_path: "/mnt/weka/gsimonyan/checkpoints/Llama-3.2-170M/dcc4447f70bf445cb5e24cfc/hf_export_step20000"
  tokenizer_path: "/mnt/weka/gsimonyan/checkpoints/Llama-3.2-170M/dcc4447f70bf445cb5e24cfc/hf_export_step20000"
  mol_tags: ["[SMILES]", "[/SMILES]"]
  pad_token: <|finetune_right_pad_id|>
  sim_tags: ["[SIMILAR]", "[/SIMILAR]"]
  device: cuda
  dtype: fp32 # bf16 / fp32

generation:
  max_new_tokens: 500
  temperature: 1.0
  do_sample: true
  repetition_penalty: 1.01
  num_return_sequences: 1

genetic:
  pool_size: 20
  num_prompts: 50
  num_similars: 3
  representation: "smiles"
  sim_vals: [0.6, 0.9]

oracle:
  name: "geam.parp1"
  max_calls: 3000
  log_dir: "results/genetic/llama3_380m/geam.parp1"
  reward_type: "geam"